version: '3'

services:
  chronograf:
    image: chronograf:alpine
    restart: always
    environment:
      PORT: '8888'
      INFLUXDB_URL: 'http://influxdb:8086'
      INFLUXDB_USERNAME: 'admin'
      INFLUXDB_PASSWORD: 'dangerous'
      REPORTING_DISABLED: 'true'
    volumes:
      - 'chronograf_data:/var/lib/chronograf'
    ports:
      - '8888:8888'
    depends_on:
      - influxdb

  telegraf:
    image: telegraf:alpine
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './telegraf.conf:/etc/telegraf/telegraf.conf:ro'
    ports:
      - '8125:8125/udp'
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:alpine
    restart: always
    environment:
      INFLUXDB_ADMIN_USER: 'admin'
      INFLUXDB_ADMIN_PASSWORD: 'dangerous'
      INFLUXDB_REPORTING_DISABLED: 'true'
    volumes:
      - './create_database.iql:/docker-entrypoint-initdb.d/create_database.iql:ro'
      - 'influxdb_data:/var/lib/influxdb'

volumes:
  chronograf_data: ~
  influxdb_data: ~
